# Generated by Django 5.1.2 on 2024-11-04 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_homes_home'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='home_model',
        ),
    ]
