# Generated by Django 5.1.2 on 2024-11-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_home_home_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_model',
            name='image',
            field=models.ImageField(upload_to='homes/'),
        ),
    ]
